Repository treolabs/treocore, pull requests merged in 2020-02, with the labels that each got.

#709 Bug fixes
  app/Treo/Resources/i18n/de_DE/Global.json
  app/Treo/Resources/i18n/en_US/Global.json
  client/modules/treo-core/src/views/fields/enum.js
Labels: bug

#711 Fixed empty value; added param for disabling empty option
  client/modules/treo-core/src/views/fields/enum.js
Labels: bug

#710 Added message for translation download error
  client/html/installation.html
  client/modules/treo-core/install/install.js
Labels: bug, feature

#713 Fixed issue with enum fields on duplication of product
  client/modules/treo-core/src/views/fields/enum.js
Labels: bug

#718 Fixes for draggable elements
  app/Treo/Resources/metadata/app/clientClassReplaceMap.json
  client/modules/treo-core/css/treo/treo-dark-theme.css
  client/modules/treo-core/src/views/admin/layouts/grid.js
Labels: bug

#719 Added reload after saving layout
  client/modules/treo-core/src/views/admin/layouts/base.js
Labels: feature

#724 Added quickCreateListDisabled param for entity filter in quick create list
  app/Treo/Resources/metadata/app/clientClassReplaceMap.json
  app/Treo/Resources/metadata/scopes/QueueItem.json
  app/Treo/Resources/metadata/scopes/TreoStore.json
  client/modules/treo-core/src/views/settings/fields/quick-create-list.js
Labels: feature

#720 Now length of the search field in modal dialog will be the entire available width
  client/modules/treo-core/css/treo/treo-dark-theme.css
  client/modules/treo-core/res/templates/record/search.tpl
  client/modules/treo-core/src/views/record/search.js
Labels: feature

#723 Added line limiter for product-variants attribute values
  client/modules/treo-core/css/treo/treo-dark-theme.css
Labels: feature

#725 Now length of the search field in modal dialog will be the entire available width
  client/modules/treo-core/src/views/record/search.js
Labels: feature
